name: Metrics

on:
  # Schedule daily updates
  schedule:
    - cron: "0 0 * * *"
  # Run workflow manually
  workflow_dispatch:
  # Run workflow when pushing on master/main
  push:
    branches:
      - master

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}

          # Options
          user: MoonGrt
          config_timezone: Asia/Shanghai
          config_display: large
          committer_message: "chore: update metrics"
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_introduction: yes

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage

          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes

          plugin_licenses: yes
          plugin_licenses_setup: npm ci

          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons

      # Move generated SVG to images directory
      - name: Move Metrics to images folder
        run: |
          mkdir -p images
          mv metrics.svg images/

      # Commit and push the changes to the current branch
      - name: Commit and Push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add images/metrics.svg
          git commit -m "chore: update metrics"
          git pull --rebase
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}