name: Profile-3D

on:
  # Schedule daily updates
  schedule:
    - cron: "0 0 * * *"
  # Run workflow manually
  workflow_dispatch:
  # Run workflow when pushing on master/main
  push:
    branches:
      - master

jobs:
  generate:
    name: Generate Profile-3D
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Checkout the repository
      - uses: actions/checkout@v3
      # Generate the GitHub profile 3D contributions SVG
      - uses: yoshi389111/github-profile-3d-contrib@0.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      # Move the generated SVG file to the images directory
      - name: Move generated SVG to images directory
        run: |
          ls
          mv profile-3d-contrib images/profile-3d
      # Commit and push changes back to the repository
      - name: Commit & Push
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add images/profile-3d/*.svg
          git commit -m "update Profile-3D" || echo "No changes to commit"
          git pull --rebase
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
