name: Profile-3D

on:
  # Schedule daily updates
  schedule:
    - cron: "0 0 * * *"
  # Run workflow manually
  workflow_dispatch:
  # Run workflow when pushing on master/main
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      # - uses: actions/checkout@v2
      # - uses: yoshi389111/github-profile-3d-contrib@0.6.0
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      #     USERNAME: ${{ github.repository_owner }}
      # - name: Commit & Push
      #   run: |
      #     git config user.name MoonGrt
      #     git config user.email 1561145394@qq.com
      #     git add -A .
      #     git commit -m "new Profile-3D"
      #     git push

      # Checkout the repository
      - uses: actions/checkout@v2
      # Generate the GitHub profile 3D contributions SVG
      - uses: yoshi389111/github-profile-3d-contrib@0.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      # Move the generated SVG file to the images directory
      - name: Move generated SVG to images directory
        run: |
          mkdir -p images
          mv *.svg images/
      # Commit and push changes back to the repository
      - name: Commit & Push
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add images/*.svg
          git commit -m "new Profile-3D" || echo "No changes to commit"
          git pull --rebase
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
