name: Snake

on:
  # Schedule daily updates
  schedule:
    - cron: "0 0 * * *"
  # Run workflow manually
  workflow_dispatch:
  # Run workflow when pushing on master
  push:
    branches:
      - master

jobs:
  generate:
    name: Generate Snack
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
      # generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
      - name: generate Snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            images/snake.svg
            images/snake-dark.svg?palette=github-dark
      # Commit and push the changes to the current branch
      - name: Commit & Push
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add images/*.svg
          git commit -m "update Snake.svg" || echo "No changes to commit"
          git pull --rebase # 同步远程分支
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
