name: Wakatime

on:
  # for manual workflow trigger
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

          SHOW_TOTAL_CODE_TIME: "False"  # 不显示总编码时间
          SHOW_PROFILE_VIEWS: "False"  # 设置为隐藏配置文件视图
          SHOW_LINES_OF_CODE: "False"   # 显示截至日期写入的代码行数
          SHOW_OS: "True"  # 显示系统
          SHOW_PROJECTS: "True"  # 显示项目
          SHOW_COMMIT: "True"  # 显示提交信息
          UPDATED_DATE_FORMAT: "False"
          DEBUG_LOGGING: "False"
          SHOW_DAYS_OF_WEEK: "True"  # 一周中不同日期进行的提交
          SHOW_LANGUAGE: "False"  # 编码语言
          SHOW_EDITORS: "True"  # 编辑器
          SHOW_LANGUAGE_PER_REPO: "True"  #  
          SHOW_SHORT_INFO: "True"  # 用户的简短趣闻信息
          SHOW_LOC_CHART: "False"  # 年份不同季度编写的代码行数
          SYMBOL_VERSION: "1"  # 设置为进度条的符号

