name: Wakatime

on:
  # Schedule daily updates
  schedule:
    - cron: "0 0 * * *"
  # Run workflow manually
  workflow_dispatch:
  # Run workflow when pushing on master
  push:
    branches:
      - master

jobs:
  generate:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

          ### content
          SHOW_TOTAL_CODE_TIME: "True"  # 总编码时间
          SHOW_PROFILE_VIEWS: "False"  # 设置为隐藏配置文件视图
          SHOW_LINES_OF_CODE: "True"  # 截至日期写入的代码行数
          SHOW_OS: "True"  # 操作系统
          SHOW_PROJECTS: "True"  # 项目
          SHOW_COMMIT: "False"  # 提交信息
          UPDATED_DATE_FORMAT: "False"
          SHOW_DAYS_OF_WEEK: "True"  # 一周中不同日期进行的提交
          SHOW_LANGUAGE: "False"  # 编码语言
          SHOW_EDITORS: "True"  # 编辑器
          SHOW_LANGUAGE_PER_REPO: "True"  # 每个仓库的编码语言
          SHOW_SHORT_INFO: "False"  # 用户的简短趣闻信息
          SHOW_LOC_CHART: "False"  # 年份不同季度编写的代码行数
          SYMBOL_VERSION: 2  # 设置为进度条的符号
          SHOW_UPDATED_DATE: "False"  # 最后更新日期
          SHOW_TIMEZONE: "True"  # 时区
          DEBUG_LOGGING: "True"  # 调试日志

          ### commit
          COMMIT_MESSAGE: Updated waka-readme graph # optional
          TARGET_BRANCH: master # optional
          TARGET_PATH: README.md # optional
          COMMITTER_NAME: MoonGrt # optional
          COMMITTER_EMAIL: 1561145394@qq.com # optional
          AUTHOR_NAME: MoonGrt # optional
          AUTHOR_EMAIL: 1561145394@qq.com # optional
